dist: trusty 
git:
  depth: 3

language: c

compiler:
  - clang
  - gcc

env:
  - CONFIGURE_OPTIONS=""
  - CONFIGURE_OPTIONS="--enable-geoip=legacy --enable-utf8"
  - CONFIGURE_OPTIONS="--enable-geoip=legacy --enable-utf8 --enable-debug"
  - CONFIGURE_OPTIONS="--enable-geoip=mmdb --enable-utf8 --with-openssl"
  - CONFIGURE_OPTIONS="--enable-geoip=legacy --enable-utf8 --with-openssl --with-getline"

addons:
  apt:
    packages:
      - libncursesw5-dev
      - libncurses5-dev
      - libgeoip-dev
      - autoconf
      - autotools-dev
      - libssl-dev
      - libmaxminddb-dev
      - gettext
      - autopoint

script:
  - autoreconf -fiv -Wall
  - ./configure CFLAGS=-Werror $CONFIGURE_OPTIONS
  - make -j
  - sudo env "PATH=$PATH" make install

after_success:
  - goaccess --version
