# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Spelling"

on:  # yamllint disable-line rule:truthy
    pull_request: null
    push:
        branches:
        - "master"
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    spell_check:
        name: "æ–‡A Spell check"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 1
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
        -
            name: "Cache pip"
            uses: "actions/cache@v3"
            with:
                path: "~/.cache/pip"
                key: "${{ runner.os }}-pip-codespell"
        -
            name: "Install codespell"
            run: |
                pip install --user 'codespell>=2.2'
        -
            name: "Search for misspellings"
            run: |
                "$(python -m site --user-base)/bin/codespell"
